### ISSUE TITLE
import error in the imfunctions.py

### ISSUE THREAD

**Issue by jalajamadhusudhanan** [Zimmer-lab/imutils#52]
pipeline breaks because of the line 
 from imutils.scopereader import MicroscopeDataReader
 'imutils.scopereader' doesn't exist after the latest change it is instead from imutils.scopedatamanager import MicroscopeDataReader

**Comment by Charles-Fieseler-Vienna** [comment]
I assume this is fixed?

**Comment by jalajamadhusudhanan** [comment]
Am 03.12.2024 15:47, schrieb Charles-Fieseler-Vienna:
